/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package social.network

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test


class AppTest {

    @Test
    fun `it works`() {
        assertThat(true).isTrue()
    }
}
